### ISSUE TITLE
 The project needs a major cleanup/update

### ISSUE THREAD

**Issue by wdlkmpx** [kdekorte/gnome-mplayer#737]
Debian Stretch does not have gnome-mplayer in its repos... I guess it's because gnome-mplayer doesn't compile there.

I think there's an issue with gconf/gsettings + dbus stuff. The most reasonable thing is to avoid both and use a plain text file with a simple syntax..

The minimum gtk version should be 2.24 (jan 2011), fix warnings about deprecated code, remove duplicated code, etc..

**Comment by glixx** [comment]
Many distributives removed gnome-mplayer. No developing. The latest release was on 24 Apr 2014.
